import type { BuildManifest } from "@vaen/schemas";

export function generateBrief(manifest: BuildManifest): string {
  const { siteConfig, template, modules, clientSlug } = manifest;

  const moduleList = modules.map((m) => `- **${m.id}** v${m.version}`).join("\n");
  const serviceList = siteConfig.services
    .map((s) => `- ${s.name}${s.price ? ` (${s.price})` : ""}`)
    .join("\n");

  const reviewItems: string[] = [];
  if (siteConfig.gallery.length === 0) {
    reviewItems.push("- No gallery images provided — consider adding project photos");
  }
  if (!siteConfig.contact.phone && !siteConfig.contact.email) {
    reviewItems.push("- No contact phone or email — visitors have no way to reach the business");
  }
  if (siteConfig.testimonials.length < 3) {
    reviewItems.push("- Fewer than 3 testimonials — more reviews would build trust");
  }
  if (!siteConfig.seo.ogImage) {
    reviewItems.push("- No OG image set — social media shares will lack a preview image");
  }

  return `# Claude Brief — ${siteConfig.business.name}

## Overview
Generated site for **${siteConfig.business.name}** (${siteConfig.business.type}).

- **Client slug:** ${clientSlug}
- **Template:** ${template.id} v${template.version}
- **Generated at:** ${manifest.generatedAt}

## Template & Modules
Template: **${template.id}**

Modules:
${moduleList || "- (none)"}

## Site Configuration

### Business
- **Name:** ${siteConfig.business.name}
- **Type:** ${siteConfig.business.type}
- **Tagline:** ${siteConfig.business.tagline}

### Services
${serviceList}

### Branding
- Primary: \`${siteConfig.branding.primaryColor}\`
- Secondary: \`${siteConfig.branding.secondaryColor}\`
- Accent: \`${siteConfig.branding.accentColor}\`
- Font: ${siteConfig.branding.fontFamily}

### Content
- **Hero:** "${siteConfig.hero.headline}"
- **Testimonials:** ${siteConfig.testimonials.length} provided
- **Gallery images:** ${siteConfig.gallery.length} provided

## Decisions Made
- Used template defaults for any missing branding fields
- Font resolved from preference: ${siteConfig.branding.fontFamily}
- SEO title auto-generated from business name + tagline
- SEO description auto-generated from business description

## Items for Review
${reviewItems.length > 0 ? reviewItems.join("\n") : "- All looks good — no major issues detected"}

## Suggestions
- Add a favicon/logo for brand recognition
- Consider adding a Google Business Profile link
- Review color contrast for accessibility (WCAG AA)

---
*Generated by vaen generator v0.1.0*
`;
}
